#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@verysync[-1]
	add ucitrack verysync
	set ucitrack.@verysync[-1].init=verysync
	commit ucitrack
EOF
chmod 755 /etc/init.d/verysync
rm -f /tmp/luci-indexcache
exit 0
