#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@baidupcs-web[-1]
	add ucitrack baidupcs-web
	set ucitrack.@baidupcs-web[-1].init=baidupcs-web
	commit ucitrack
EOF
chmod 755 /etc/init.d/baidupcs-web
rm -f /tmp/luci-indexcache
exit 0
